# This is a basic workflow to help you get started with Actions

name: "Create 'This month in mathlib' PR"

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  push:
    branches: [automate-this-month-in]  # hack so that I can test this in the PR

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          path: blog
      - uses: actions/checkout@v3
        with:
          repository: leanprover-community/mathlib
          path: mathlib

      # Runs a single command using the runners shell
      - name: Generate the blog post
        id: generate
        run: |
          cd blog
          # hack taken from https://www.gnu.org/software/coreutils/manual/html_node/Relative-items-in-date-strings.html
          date="$(date +%Y-%m-15) -1 month"
          date_info=$(date --date="$date" +"%Y %-m %m");
          echo "::set-output name=iso-date::$(date --date="$date" +"%Y-%m")"
          ./monthly_blog.sh "$(date --date="$date" +"%Y")" "$(date --date="$date" +"%-m")" ../mathlib

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: this-month-in-mathlib/${{ steps.generate.iso-date}}
          title: This month in mathlib (${{ steps.generate.iso-date}})
