name: "Create 'This month in mathlib' PR"

on:
  # Allows us to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  push:
    branches: [automate-this-month-in]  # hack so that I can test this in the PR

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: blog
      - uses: actions/checkout@v3
        with:
          repository: leanprover-community/mathlib
          path: mathlib

      - name: Generate the blog post
        id: generate
        run: |
          cd blog
          # hack taken from https://www.gnu.org/software/coreutils/manual/html_node/Relative-items-in-date-strings.html
          date="$(date +%Y-%m-15) -1 month"
          date_info=$(date --date="$date" +"%Y %-m %m");
          echo "::set-output name=iso-date::$(date --date="$date" +"%Y-%m")"
          ./monthly-blog.sh "$(date --date="$date" +"%Y")" "$(date --date="$date" +"%-m")" ../mathlib

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: this-month-in-mathlib/${{ steps.generate.iso-date}}
          title: This month in mathlib (${{ steps.generate.iso-date}})
